export const PROFILE_VERSION = 1;

export const FACTIONS = Object.freeze({
  orthodox: Object.freeze({
    id: "orthodox",
    name: "Chính Đạo",
    title: "Thanh Vân Kiếm Tông",
    description: "Kiếm tu chính trực, cân bằng giữa tốc độ, phòng thủ và kiếm khí.",
    color: "#77ddff",
    accentColor: "#e7fbff",
    bonus: Object.freeze({ stat: "dodge", amount: 0.08 }),
  }),
  demonic: Object.freeze({
    id: "demonic",
    name: "Ma Đạo",
    title: "Huyết Sát Ma Môn",
    description: "Đổi sự an toàn lấy bạo kích và sức ép tấn công mãnh liệt.",
    color: "#d84b71",
    accentColor: "#ffb0c2",
    bonus: Object.freeze({ stat: "criticalChance", amount: 0.1 }),
  }),
  heretic: Object.freeze({
    id: "heretic",
    name: "Tà Đạo",
    title: "Vạn Độc Cốc",
    description: "Lối đánh khó đoán, bào mòn đối thủ và hồi phục bằng hút sinh lực.",
    color: "#74d96c",
    accentColor: "#caffaa",
    bonus: Object.freeze({ stat: "lifeSteal", amount: 0.06 }),
  }),
});

export const ABILITIES = Object.freeze({
  basic: Object.freeze({
    id: "basic",
    input: "Mouse0",
    name: "Kiếm Khí",
    cost: 0,
    cooldown: 0.42,
    range: 4.8,
    damage: 18,
    color: "#8eeeff",
    kind: "attack",
    description: "Chém nhanh và phóng một luồng kiếm khí ở cự ly gần.",
  }),
  q: Object.freeze({
    id: "q",
    input: "Q",
    name: "Định Thân Phù",
    cost: 18,
    cooldown: 5,
    range: 14,
    damage: 22,
    color: "#72d8ff",
    kind: "control",
    description: "Phóng linh phù gây sát thương và trói mục tiêu trong thời gian ngắn.",
  }),
  e: Object.freeze({
    id: "e",
    input: "E",
    name: "Vạn Kiếm Quy Tông",
    cost: 32,
    cooldown: 8,
    range: 9,
    damage: 44,
    color: "#bcefff",
    kind: "area",
    description: "Triệu hồi kiếm ảnh quét một vùng hình quạt phía trước.",
  }),
  r: Object.freeze({
    id: "r",
    input: "R",
    name: "Trảm Tiên Trảm Địa",
    cost: 42,
    cooldown: 12,
    range: 11,
    damage: 78,
    color: "#ffd36e",
    kind: "burst",
    description: "Tụ lực rồi tung một nhát chém đơn mục tiêu có sức phá giáp lớn.",
  }),
  f: Object.freeze({
    id: "f",
    input: "F",
    name: "Khiên Linh Lực",
    cost: 28,
    cooldown: 14,
    range: 0,
    damage: 0,
    color: "#6d9dff",
    kind: "defence",
    description: "Tạo pháp thuẫn hấp thụ sát thương trong một khoảng thời gian.",
  }),
  g: Object.freeze({
    id: "g",
    input: "G",
    name: "Hóa Thần Biến",
    cost: 100,
    cooldown: 45,
    range: 13,
    damage: 120,
    color: "#d879ff",
    kind: "ultimate",
    description: "Giải phóng toàn bộ chân nguyên, gây sát thương lớn và cường hóa tạm thời.",
  }),
});

export const REALMS = Object.freeze([
  Object.freeze({
    id: "qi_refining",
    order: 1,
    name: "Luyện Khí Kỳ",
    shortName: "Luyện Khí",
    stages: 13,
    requiredForNext: 100,
    nextId: "foundation",
    prototypeStatus: "locked",
    breakthrough: "Tích đủ linh khí và đả thông kinh mạch.",
  }),
  Object.freeze({
    id: "foundation",
    order: 2,
    name: "Trúc Cơ Kỳ",
    shortName: "Trúc Cơ",
    stages: 1,
    requiredForNext: 100,
    nextId: "golden_core",
    prototypeStatus: "playable-start",
    breakthrough: "Sống sót qua ba đợt Tiểu Lôi Kiếp để kết Kim Đan.",
  }),
  Object.freeze({
    id: "golden_core",
    order: 3,
    name: "Kim Đan Kỳ",
    shortName: "Kim Đan",
    stages: 1,
    requiredForNext: 500,
    nextId: "nascent_soul",
    prototypeStatus: "playable-destination",
    breakthrough: "Ngưng tụ Kim Đan và mở khóa Ngự Kiếm Phi Hành.",
  }),
  Object.freeze({
    id: "nascent_soul",
    order: 4,
    name: "Nguyên Anh Kỳ",
    shortName: "Nguyên Anh",
    stages: 1,
    requiredForNext: 2_500,
    nextId: "spirit_transformation",
    prototypeStatus: "locked",
    breakthrough: "Vượt Đại Lôi Kiếp sáu đợt; thất bại có thể tổn hại linh căn.",
  }),
  Object.freeze({
    id: "spirit_transformation",
    order: 5,
    name: "Hóa Thần Kỳ",
    shortName: "Hóa Thần",
    stages: 1,
    requiredForNext: 12_000,
    nextId: "void_refinement",
    prototypeStatus: "locked",
    breakthrough: "Đối mặt và chiến thắng Tâm Ma của chính mình.",
  }),
  Object.freeze({
    id: "void_refinement",
    order: 6,
    name: "Luyện Hư Kỳ",
    shortName: "Luyện Hư",
    stages: 1,
    requiredForNext: 60_000,
    nextId: "body_integration",
    prototypeStatus: "locked",
    breakthrough: "Thu thập đủ năm nguyên liệu Ngũ Hành của trời đất.",
  }),
  Object.freeze({
    id: "body_integration",
    order: 7,
    name: "Hợp Thể Kỳ",
    shortName: "Hợp Thể",
    stages: 1,
    requiredForNext: 300_000,
    nextId: "mahayana",
    prototypeStatus: "locked",
    breakthrough: "Hợp nhất thần thức, Nguyên Anh và nhục thân.",
  }),
  Object.freeze({
    id: "mahayana",
    order: 8,
    name: "Đại Thừa Kỳ",
    shortName: "Đại Thừa",
    stages: 1,
    requiredForNext: 100_000_000,
    nextId: "tribulation",
    prototypeStatus: "locked",
    breakthrough: "Lĩnh ngộ pháp tắc và tích lũy một trăm triệu điểm chân nguyên.",
  }),
  Object.freeze({
    id: "tribulation",
    order: 9,
    name: "Độ Kiếp Kỳ",
    shortName: "Độ Kiếp",
    stages: 1,
    requiredForNext: null,
    nextId: null,
    prototypeStatus: "locked",
    breakthrough: "Chống chọi Cửu Thiên Lôi Kiếp để phi thăng.",
  }),
]);

export const PROTOTYPE_SCOPE = Object.freeze({
  startRealmId: "foundation",
  breakthroughTargetId: "golden_core",
  requiredCultivation: 100,
  lightningWaves: 3,
});

export const QUEST_PHASES = Object.freeze([
  Object.freeze({
    id: "arrival",
    order: 0,
    title: "Nhập Điện",
    objective: "Tiến vào sân điện và làm quen với điều khiển.",
    nextId: "purge",
  }),
  Object.freeze({
    id: "purge",
    order: 1,
    title: "Thanh Trừ Ma Ảnh",
    objective: "Đánh bại những ma ảnh đang chiếm giữ sân điện.",
    nextId: "boss",
  }),
  Object.freeze({
    id: "boss",
    order: 2,
    title: "Hộ Pháp Sa Ngã",
    objective: "Đánh bại Ma Ảnh Hộ Pháp.",
    nextId: "cultivate",
  }),
  Object.freeze({
    id: "cultivate",
    order: 3,
    title: "Tĩnh Tọa Tụ Khí",
    objective: "Tích đủ 100 tu vi để chuẩn bị đột phá.",
    nextId: "breakthrough",
  }),
  Object.freeze({
    id: "breakthrough",
    order: 4,
    title: "Tiểu Lôi Kiếp",
    objective: "Sống sót qua ba đợt thiên lôi để kết thành Kim Đan.",
    nextId: "complete",
  }),
  Object.freeze({
    id: "complete",
    order: 5,
    title: "Kim Đan Sơ Thành",
    objective: "Đã hoàn thành nội dung của bản chơi thử.",
    nextId: null,
  }),
]);

export const ENEMY_ARCHETYPES = Object.freeze({
  spirit_fox: Object.freeze({ id: "spirit_fox", name: "Linh Hồ Con", role: "trash", maxHp: 38, speed: 2.35, damage: 4, attackRange: 1.35, aggroRange: 9, attackCooldown: 1.65, cultivationReward: 3, color: "#91f6dd", scale: 0.58, boss: false }),
  flame_imp: Object.freeze({ id: "flame_imp", name: "Tiểu Hỏa Ma", role: "trash", maxHp: 45, speed: 2.1, damage: 5, attackRange: 1.5, aggroRange: 10, attackCooldown: 1.75, cultivationReward: 4, color: "#c94872", scale: 0.62, boss: false }),
  spirit_wolf: Object.freeze({
    id: "spirit_wolf",
    name: "U Minh Yêu Lang",
    role: "skirmisher",
    maxHp: 38.4,
    speed: 3.51,
    damage: 5.85,
    attackRange: 1.7,
    aggroRange: 9.36,
    attackCooldown: 1.25,
    cultivationReward: 12,
    color: "#7fc5a0",
    scale: 0.85,
    boss: false,
  }),
  rogue_cultivator: Object.freeze({
    id: "rogue_cultivator",
    name: "Tà Tu Hắc Phù",
    role: "ranged",
    maxHp: 49.2,
    speed: 2.57,
    damage: 7.8,
    attackRange: 8.5,
    aggroRange: 11.52,
    attackCooldown: 1.8,
    cultivationReward: 16,
    color: "#9c70c8",
    scale: 1,
    boss: false,
  }),
  stone_guardian: Object.freeze({
    id: "stone_guardian",
    name: "Thạch Giáp Khôi Lỗi",
    role: "bruiser",
    maxHp: 87,
    speed: 1.87,
    damage: 11.7,
    attackRange: 2.2,
    aggroRange: 8.64,
    attackCooldown: 2.1,
    cultivationReward: 24,
    color: "#c49b72",
    scale: 1.25,
    boss: false,
  }),
  fallen_guardian: Object.freeze({
    id: "fallen_guardian",
    name: "Ma Ảnh Hộ Pháp",
    role: "boss",
    maxHp: 312,
    speed: 2.34,
    damage: 15.6,
    attackRange: 3,
    aggroRange: 17.28,
    attackCooldown: 1.6,
    cultivationReward: 55,
    color: "#d94665",
    scale: 1.65,
    boss: true,
  }),
});

export const DEFAULT_PROFILE = Object.freeze({
  version: PROFILE_VERSION,
  name: "Vô Danh",
  factionId: "orthodox",
  realmId: PROTOTYPE_SCOPE.startRealmId,
  cultivation: 0,
  questPhase: "arrival",
  breakthroughActive: false,
  lightningWave: 0,
  settings: Object.freeze({
    masterVolume: 0.8,
    effectsVolume: 0.9,
    mouseSensitivity: 1,
  }),
});

