const clamp=(value,min,max)=>Math.max(min,Math.min(max,value));

export class GoldDropSystem {
  constructor({screen,pickupRadius=100,onPickup,audio}={}){this.screen=screen;this.pickupRadius=pickupRadius;this.onPickup=onPickup;this.audio=audio;this.drops=[];this.sequence=0;}
  spawnGoldLoot(x,z,amount,{boss=false}={}){const total=Math.max(0,Math.floor(Number(amount)||0));if(!total)return [];const count=clamp(boss?Math.ceil(total/18):Math.ceil(total/8),1,boss?14:5),base=Math.floor(total/count),remainder=total-base*count;const created=[];for(let i=0;i<count;i++){const angle=i/count*Math.PI*2+Math.random()*.35,distance=(boss?1.8:1.05)*(0.35+Math.random());const drop={id:`gold-${++this.sequence}`,x,z,groundX:x+Math.cos(angle)*distance,groundZ:z+Math.sin(angle)*distance,amount:base+(i<remainder?1:0),height:0,vy:5.5+Math.random()*2.5,age:0,state:'bounce',magnetTime:0};this.drops.push(drop);created.push(drop);}this.audio?.play('coin-drop');return created;}
  update(dt,player){for(let i=this.drops.length-1;i>=0;i--){const drop=this.drops[i];drop.age+=dt;if(drop.state==='bounce'){drop.x+=(drop.groundX-drop.x)*Math.min(1,dt*7);drop.z+=(drop.groundZ-drop.z)*Math.min(1,dt*7);drop.height+=drop.vy*dt;drop.vy-=18*dt;if(drop.height<=0){drop.height=0;if(Math.abs(drop.vy)>2){drop.vy=Math.abs(drop.vy)*.38;}else drop.state='idle';}}const dx=player.x-drop.x,dz=player.z-drop.z,pixelDistance=Math.hypot(dx*18,dz*12);if(drop.state!=='bounce'&&pixelDistance<=this.pickupRadius)drop.state='magnet';if(drop.state==='magnet'){drop.magnetTime+=dt;const speed=8+drop.magnetTime*28,t=Math.min(1,dt*speed);drop.x+=dx*t;drop.z+=dz*t;drop.height+=(14-drop.height)*Math.min(1,dt*10);if(pixelDistance<15){this.drops.splice(i,1);this.onPickup?.(drop.amount,drop);this.audio?.play('coin');}}}}
  render(ctx){for(const drop of this.drops){const p=this.screen({x:drop.x,z:drop.z});const y=p.y-drop.height,flash=.82+.18*Math.sin(drop.age*15);ctx.save();ctx.globalAlpha=flash;ctx.fillStyle='rgba(0,0,0,.28)';ctx.beginPath();ctx.ellipse(p.x,p.y+2,7,3,0,0,Math.PI*2);ctx.fill();ctx.translate(Math.round(p.x),Math.round(y-5));const squash=.42+.58*Math.abs(Math.sin(drop.age*11));ctx.scale(squash,1);ctx.fillStyle='#7b4310';ctx.fillRect(-5,-5,10,10);ctx.fillStyle='#ffd84b';ctx.fillRect(-4,-5,8,9);ctx.fillStyle='#fff1a0';ctx.fillRect(-2,-4,3,2);ctx.restore();if(drop.age<1.1){ctx.save();ctx.globalAlpha=clamp(1-drop.age/1.1,0,1);ctx.fillStyle='#ffe25f';ctx.strokeStyle='#4b2708';ctx.lineWidth=3;ctx.font='bold 11px monospace';ctx.textAlign='center';const label=`+${drop.amount} Vàng`;ctx.strokeText(label,p.x,y-18-drop.age*12);ctx.fillText(label,p.x,y-18-drop.age*12);ctx.restore();}}}
  clear(){this.drops.length=0;}
}
