import { getSectCombatData } from './SectData.js';
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
export class VFXManager{
  constructor({screen,audio}){this.screen=screen;this.audio=audio;this.effects=[];}
  cast({faction,slot,origin,direction,target}){const sect=getSectCombatData(faction),style=sect.vfx[slot]??sect.vfx.basic;this.audio?.play(sect.sound);const base={style,faction,x:origin.x,z:origin.z,dx:direction.x,dz:direction.z,tx:target?.x??origin.x+direction.x*5,tz:target?.z??origin.z+direction.z*5,life:style.includes('Mist')||style.includes('Skulls')?1.8:.8,max:style.includes('Mist')||style.includes('Skulls')?1.8:.8,colors:[sect.primary,sect.secondary,sect.accent]};this.effects.push(base);if(['flyingSwords','swordRain','myriadSwords','demonChains','toxicSkulls'].includes(style))for(let i=0;i<7;i++)this.effects.push({...base,life:base.life+i*.04,max:base.max+i*.04,offset:(i-3)*.38,seed:Math.random()});return style;}
  update(dt){for(let i=this.effects.length-1;i>=0;i--){const e=this.effects[i];e.life-=dt;if(['swordWave','bloodSlash','venomBlade','venomDart','flyingSwords','serpentFang'].includes(e.style)){e.x+=e.dx*dt*13;e.z+=e.dz*dt*13;}if(e.life<=0)this.effects.splice(i,1);}}
  render(ctx){for(const e of this.effects){const p=this.screen(e),t=clamp(e.life/e.max,0,1),age=1-t;ctx.save();ctx.globalAlpha=Math.min(1,t*1.5);ctx.strokeStyle=e.colors[0];ctx.fillStyle=e.colors[0];ctx.shadowColor=e.colors[1];ctx.shadowBlur=10;const angle=Math.atan2(e.dz,e.dx);if(/sword|Sword|Slash|Blade|Dart|Fang|Reaver/.test(e.style)){ctx.translate(p.x,p.y-12+(e.offset??0)*8);ctx.rotate(angle);ctx.lineWidth=e.style==='bloodReaver'?8:3;ctx.beginPath();ctx.moveTo(-18,0);ctx.quadraticCurveTo(0,-18-(e.seed??0)*10,28,0);ctx.stroke();ctx.fillStyle=e.colors[2];ctx.fillRect(7,-2,22,3);}else if(e.style==='holyBeam'){ctx.fillStyle=e.colors[2];ctx.globalAlpha=t*.75;ctx.fillRect(p.x-7,p.y-110,14,110);ctx.fillStyle='#fff';ctx.fillRect(p.x-2,p.y-125,4,125);}else if(e.style==='goldBarrier'){ctx.strokeStyle=e.colors[2];ctx.lineWidth=5;ctx.beginPath();ctx.ellipse(p.x,p.y-12,30+age*8,18+age*4,0,0,Math.PI*2);ctx.stroke();}else if(/bloodFlame|Nova|abyssBurst/.test(e.style)){ctx.fillStyle=e.colors[Math.floor(age*12)%3];ctx.globalAlpha=t*.55;ctx.beginPath();ctx.arc(p.x,p.y,18+age*55,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#18040a';ctx.lineWidth=4;ctx.stroke();}else if(e.style==='demonChains'){ctx.strokeStyle=e.colors[0];ctx.lineWidth=3;ctx.setLineDash([7,5]);ctx.beginPath();ctx.moveTo(p.x,p.y-10);ctx.lineTo(this.screen({x:e.tx,z:e.tz}).x,this.screen({x:e.tx,z:e.tz}).y);ctx.stroke();}else if(e.style==='shadowStep'){ctx.fillStyle=e.colors[1];ctx.globalAlpha=t*.55;ctx.beginPath();ctx.ellipse(p.x-e.dx*age*70,p.y-e.dz*age*45-12,18,28,0,0,Math.PI*2);ctx.fill();}else{const target=this.screen({x:e.tx+(e.offset??0),z:e.tz+(e.offset??0)});ctx.fillStyle=e.colors[Math.floor((e.seed??0)*3)];ctx.globalAlpha=.16+t*.35;ctx.beginPath();ctx.arc(target.x,target.y-8,18+age*35,0,Math.PI*2);ctx.fill();for(let i=0;i<4;i++){ctx.globalAlpha=t;ctx.beginPath();ctx.arc(target.x+Math.sin(i*2.2+age*6)*22,target.y-12-Math.cos(i+age*5)*16,3+(i%2)*2,0,Math.PI*2);ctx.fill();}}ctx.restore();}}
  clear(){this.effects.length=0;}
}
